name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - gh-actions-deploy

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install Node dependencies
        run: npm ci

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse

      - id: date
        run: echo "date=$(TZ=America/Lima date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - id: cache-data
        uses: actions/cache@v4
        with:
          path: |
            src/.observablehq/cache
          key: data-${{ hashFiles('src/data/*') }}-${{ steps.date.outputs.date }}

      - if: steps.cache-data.outputs.cache-hit == 'true'
        run: find src/.observablehq/cache -type f -exec touch {} +

      - name: Build
        run: npm run build

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
